sudo: required

service: 
  - docker

before_script: 
  - docker build -t jinugeorge2290/docker-react -f Dockerfile.dev .

script: 
  - docker run jinugeorge2290/docker-react npm run test -- --coverage